name: Build and Excecute Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Excecute du script python
      run: python main.py

    - name: Installation des d√©pendances
      run: pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic

    - name: test with pytest
      run: coverage run -m pytest --profile